// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA84gMNiwQTI8xzHnIYfdV0tUl5yFjhF0M',
    appId: '1:472434093632:web:e12677b9f98ebeb7fff9a5',
    messagingSenderId: '472434093632',
    projectId: 'restaurantmanagement-70d97',
    authDomain: 'restaurantmanagement-70d97.firebaseapp.com',
    storageBucket: 'restaurantmanagement-70d97.appspot.com',
    measurementId: 'G-G9CS37N5WT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBnGVhjNEn_hz0ByHFchl4_Rhi46ZJHO4',
    appId: '1:472434093632:android:4cdd4022cd796f27fff9a5',
    messagingSenderId: '472434093632',
    projectId: 'restaurantmanagement-70d97',
    storageBucket: 'restaurantmanagement-70d97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDldw6a-oIfzc8mtgAfkq1Z4IapwhMRoVE',
    appId: '1:472434093632:ios:7892908622d3b809fff9a5',
    messagingSenderId: '472434093632',
    projectId: 'restaurantmanagement-70d97',
    storageBucket: 'restaurantmanagement-70d97.appspot.com',
    iosClientId: '472434093632-ner82pftppaeeffrpmtneua3m13puili.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDldw6a-oIfzc8mtgAfkq1Z4IapwhMRoVE',
    appId: '1:472434093632:ios:c6cccd7bea99b01efff9a5',
    messagingSenderId: '472434093632',
    projectId: 'restaurantmanagement-70d97',
    storageBucket: 'restaurantmanagement-70d97.appspot.com',
    iosClientId: '472434093632-83hlh45it6lau1tn6e2dtsgnm76i0df1.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantManagement.RunnerTests',
  );
}
